### ISSUE TITLE
Universal Hex packing efficiency: can we increase it?

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/spec-universal-hex#5]
## How large are the Universal Hexes?

With 'Universal Hex' turned on in MakeCode today the file is definitely really large - we go from ~600k hex file to ~1.7M  - 2.7 times the original file - I'd expected ~2.

Looking in more detail:
V1 Hex with 'normal' encoding: 625kB
V2 Hex with 'normal' encoding: 779kB

Total 'concatenation size' 1404 --> Expansion: **2.24 times the original size** with 'normal' hex (IE if we just stuck them together)
Compared to our Universal Hex size, **1762kB, 2.7 times original**

As hex files are typically generated in the browser this isn't a huge concern but it's a noticeable increase and if we are to add other things it'll grow very fast.

## Sanity check for the expansion:

Based on the layout in the docs for v2, a 440Byte line becomes a 512B line, which gives us 1.16, if both the 'thin' hexes above were expanded this amount we should be able to reach 1.62MB - seems like we have a small amount of other overhead beyond the blocks... @microbit-carlos do you know - Is that padding in some blocks because we only have one extended linear address per block? Or something else?

## Reducing the file size

However, there are some more vicious options for the v2 part of the hex, that make the file slightly less normal but smaller.

The header portion is 36 bytes, so if we have a single line to follow this, it should be 476 bytes - which is a 'byte count' of 232 in the record.
(I've thrown away the end of block record - is that allowed?)

If we take the line length up to 236 bytes in v2 portions, we can take a 'raw' v2 file from 779kB to 566kB.
Given that for every 476 bytes we're going to add 36 we get a 1.076 size penalty for the universal hex, meaning 566*1.076 = 609kB
This gives a block a bit like this....
```
:020000040000FA
:0400000A9901C0DEBA
:E800E800FF08000009090000130900001D09000027090000310900003B0900001FB500F003F88DE80F001FBD00F0ACBC40F6FC7108684FF01022401C08D00868401C09D00868401C04D0086800F037BA9069F5E79069F9E7704770B50B46010B184400F6FF70040B4FF080500022090303692403406943431D1B104600F048FA29462046BDE8704000F042BAF0B54FF6FF734FF4B4751A466E1E11E0A94201D3344600E00C46091B30F8027B641E3B441A44F9D19CB204EB134394B204EB12420029EBD198B200EB134002EB124140EA0140F0BDF34992B00446D1E90001CDE91001FF224021684600F0F4FB9A
```
This would give us closer to 2x for a typical v2 program.

(It's still a long way from what we could achieve if we weren't using hex, of course...)

@microbit-carlos was against using this very long line hex for the way it might break existing parsers. I'd argue if we did this for the v2 part of the hex only, it might be fine? However, the example below that DAPLink maxes out at a byte count of 0x20 is a good example of the way things might break...

If we feel the 1.7Mb 'typical' hex file is unreasonably large, we would need to remedy this ASAP.

Am I missing anything important about the structure for it to parse properly?

@gerargz at the moment, if I go above line length of 76 (which is byte count of 32) then DAPLink rejects the file. Is this a hard limit or could we take longer lines for v2?
@mmoskal would doing something like this be trivial for MakeCode?
@microbit-mark how significant do you think the file size will be for most users?

**Comment by microbit-carlos** [comment]
The accepted changes are included in v0.4.0 of the spec: https://github.com/microbit-foundation/spec-universal-hex/pull/10
